### ISSUE TITLE
Incorrect train layout

### ISSUE THREAD

**Issue by vespino** [mt-xing/coaster-seat-guru#11]
This train layout is incorrect: https://coasterseatguru.com/results/?id=800

**Comment by mt-xing** [comment]
Thank you. It has been fixed.

**Comment by vespino** [comment]
Still not correct. The first car only has 1 row.

**Comment by mt-xing** [comment]
Sorry, was looking at the wrong RCDB page. Do you know what the layout is supposed to look like? RCDB claims 48 riders in 12 cars, which seems to imply every car has 4 riders, including the first. But the picture of the front car indeed only has one row. I haven't been on this ride before; have you?

**Comment by vespino** [comment]
I don’t recall riding it, but most Mack powered coasters have 19 rows, 1 row in the zero car and 9x2x2 lead cars. In this video (at 38 seconds) you can count the cars: https://youtu.be/y_dDm6hHQEY?si=trfgu_1TrKlYi8xO. Might be the 12 mentioned.

**Comment by mt-xing** [comment]
I count 10 normal cars plus an additional locomotive in the front based on the video, so I'm putting in 21 rows for now. Let me know if that's still incorrect.
