### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by vespino** [mt-xing/coaster-seat-guru#7]
![62C33CD4-517D-4A05-8894-5A98B45BA943](https://user-images.githubusercontent.com/6991325/212498627-3687ffcd-cea2-4472-833e-9c842d4696bd.png)

**Comment by mt-xing** [comment]
Apologies for the long wait; was off riding Iron Gwazi last week. Fix should be rolling out now.

**Comment by vespino** [comment]
You pick your priorities wisely 👌🏻
